"""Introspect the argparse tree and emit a static bash completion script.

Run via ``make completion`` (``python3 -m wb_cli._gen_completion``). The result
is written to ``data/bash-completion/wb-cli`` and shipped by the Debian package
to ``/usr/share/bash-completion/completions/wb-cli``.

Structural only: it completes commands, subcommands and option flags — not live
values (device addresses, template names, ports). That keeps completion instant
and offline; the wb-cli process is never spawned on <Tab>.

Like ``_gen_registry`` this walks the same parser code the CLI builds at
runtime, so the completion never drifts from the actual command tree as long as
it is regenerated (the build does so; ``tests/test_completion.py`` guards it).
"""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

from wb_cli._registry import BUILTIN_PLUGINS

# Global flags handled by cli.main before dispatch; valid alongside any command.
GLOBAL_OPTS = "--json --human"
# Flags that only make sense at the top level (before a command is chosen).
ROOT_OPTS = "--json --human --version --help"


def _sanitize(name: str) -> str:
    """Command/subcommand name -> a valid bash variable suffix."""
    return name.replace("-", "_")


def _option_strings(parser: argparse.ArgumentParser) -> list[str]:
    """Every option flag on a parser, de-duplicated, argparse order preserved."""
    seen: list[str] = []
    for action in parser._actions:  # pylint: disable=protected-access
        for flag in action.option_strings:
            if flag not in seen:
                seen.append(flag)
    return seen


def _subparsers_action(parser: argparse.ArgumentParser):
    for action in parser._actions:  # pylint: disable=protected-access
        if isinstance(action, argparse._SubParsersAction):  # pylint: disable=protected-access
            return action
    return None


def collect() -> dict:
    """Return {command: {"opts": [...], "subs": {sub: [opts...]}}} for every plugin."""
    tree: dict = {}
    for name, (module_path, _help) in sorted(BUILTIN_PLUGINS.items()):
        try:
            module = importlib.import_module(module_path)
            plug = module.PLUGIN
        except (ImportError, AttributeError):
            continue

        root = argparse.ArgumentParser(prog="wb-cli")
        subparsers = root.add_subparsers(dest="cmd")
        plug.register(subparsers)
        parser = subparsers.choices.get(name)
        if parser is None:
            continue

        entry: dict = {"opts": _option_strings(parser), "subs": {}}
        sub_action = _subparsers_action(parser)
        if sub_action is not None:
            for sub_name, sub_parser in sub_action.choices.items():
                entry["subs"][sub_name] = _option_strings(sub_parser)
        tree[name] = entry
    return tree


def render(tree: dict) -> str:
    commands = " ".join(sorted(tree))
    lines: list[str] = [
        "# wb-cli bash completion.",
        "# GENERATED by wb_cli/_gen_completion.py -- do not edit by hand.",
        "# Regenerate with `make completion`.",
        "",
        "_wb_cli()",
        "{",
        "    local cur prev words cword",
        "    if declare -F _init_completion >/dev/null 2>&1; then",
        "        _init_completion || return",
        "    else",
        "        COMPREPLY=()",
        '        cur="${COMP_WORDS[COMP_CWORD]}"',
        '        prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '        words=("${COMP_WORDS[@]}")',
        '        cword="$COMP_CWORD"',
        "    fi",
        "",
        f"    local root_opts='{ROOT_OPTS}'",
        f"    local global_opts='{GLOBAL_OPTS}'",
        f"    local commands='{commands}'",
        "",
        "    # Per-command option/subcommand tables (hyphens -> underscores).",
    ]

    for name in sorted(tree):
        entry = tree[name]
        var = _sanitize(name)
        lines.append(f"    local opts_{var}='{' '.join(entry['opts'])}'")
        if entry["subs"]:
            lines.append(f"    local subs_{var}='{' '.join(sorted(entry['subs']))}'")
            for sub_name in sorted(entry["subs"]):
                sub_var = _sanitize(sub_name)
                sub_opts = " ".join(entry["subs"][sub_name])
                lines.append(f"    local opts_{var}_{sub_var}='{sub_opts}'")

    lines += [
        "",
        "    # Identify the command and (if the command has any) its subcommand,",
        "    # skipping option flags. Global flags may sit anywhere in argv.",
        "    local i w cmd='' sub=''",
        "    for (( i=1; i < cword; i++ )); do",
        '        w="${words[i]}"',
        '        [[ "$w" == -* ]] && continue',
        '        if [[ -z "$cmd" ]]; then',
        '            cmd="$w"',
        "            continue",
        "        fi",
        '        local subs_var="subs_${cmd//-/_}"',
        '        if [[ -n "${!subs_var:-}" && -z "$sub" ]]; then',
        '            sub="$w"',
        "        fi",
        "    done",
        "",
        "    # No command yet: complete command names, or top-level flags.",
        '    if [[ -z "$cmd" ]]; then',
        '        if [[ "$cur" == -* ]]; then',
        '            COMPREPLY=( $(compgen -W "$root_opts" -- "$cur") )',
        "        else",
        '            COMPREPLY=( $(compgen -W "$commands" -- "$cur") )',
        "        fi",
        "        return 0",
        "    fi",
        "",
        '    local subs_var="subs_${cmd//-/_}"',
        '    local cmd_subs="${!subs_var:-}"',
        "",
        "    # Command takes subcommands but none chosen yet: complete those,",
        "    # or the command's own flags.",
        '    if [[ -n "$cmd_subs" && -z "$sub" ]]; then',
        '        if [[ "$cur" == -* ]]; then',
        '            local opts_var="opts_${cmd//-/_}"',
        '            COMPREPLY=( $(compgen -W "${!opts_var:-} $global_opts" -- "$cur") )',
        "        else",
        '            COMPREPLY=( $(compgen -W "$cmd_subs" -- "$cur") )',
        "        fi",
        "        return 0",
        "    fi",
        "",
        "    # A subcommand is chosen, or the command has none: complete flags.",
        "    local opts_var",
        '    if [[ -n "$sub" ]]; then',
        '        opts_var="opts_${cmd//-/_}_${sub//-/_}"',
        "    else",
        '        opts_var="opts_${cmd//-/_}"',
        "    fi",
        '    COMPREPLY=( $(compgen -W "${!opts_var:-} $global_opts" -- "$cur") )',
        "    return 0",
        "}",
        "complete -F _wb_cli wb-cli",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    tree = collect()
    target = Path(__file__).resolve().parent.parent / "data" / "bash-completion" / "wb-cli"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(tree), encoding="utf-8")
    print(f"wrote {target} ({len(tree)} commands)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
